/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : string,
  'text' : string,
  'user' : Principal,
  'timestamp' : Time,
}
export type ExternalBlob = Uint8Array;
export interface Report {
  'timestamp' : Time,
  'reporter' : Principal,
  'reason' : string,
  'videoId' : string,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'email' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : string,
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'views' : bigint,
  'description' : string,
  'videoFile' : ExternalBlob,
  'category' : string,
  'uploader' : Principal,
  'uploadTime' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], Comment>,
  'addVideoToPlaylist' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPlaylist' : ActorMethod<[string], undefined>,
  'deleteComment' : ActorMethod<[string, string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getAllReports' : ActorMethod<[], Array<[string, Array<Report>]>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlatformStats' : ActorMethod<
    [],
    { 'totalReports' : bigint, 'totalVideos' : bigint, 'totalUsers' : bigint }
  >,
  'getTrendingVideos' : ActorMethod<[], Array<Video>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoReports' : ActorMethod<[string], Array<Report>>,
  'getVideosByCategory' : ActorMethod<[string], Array<Video>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeVideo' : ActorMethod<[string], bigint>,
  'removeReportedVideo' : ActorMethod<[string], undefined>,
  'reportVideo' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchVideos' : ActorMethod<[string], Array<Video>>,
  'subscribeToChannel' : ActorMethod<[Principal], undefined>,
  'uploadVideo' : ActorMethod<
    [string, string, string, ExternalBlob, [] | [ExternalBlob], string],
    Video
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];