/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAction {
  'id' : bigint,
  'admin' : Principal,
  'actionType' : string,
  'timestamp' : Time,
  'details' : string,
  'affectedResource' : string,
}
export interface Comment {
  'id' : string,
  'text' : string,
  'user' : Principal,
  'timestamp' : Time,
}
export type ExternalBlob = Uint8Array;
export interface PlatformSettings {
  'maxVideoSizeMB' : bigint,
  'allowedCategories' : Array<string>,
  'moderationPolicies' : string,
}
export interface PlaylistView { 'name' : string, 'videos' : Array<string> }
export interface Report {
  'timestamp' : Time,
  'reporter' : Principal,
  'reason' : string,
  'videoId' : string,
}
export interface SuspensionStatus {
  'status' : { 'active' : null } |
    { 'banned' : null } |
    { 'suspended' : null },
  'admin' : Principal,
  'timestamp' : Time,
  'reason' : string,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'email' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : string,
  'title' : string,
  'featured' : boolean,
  'thumbnail' : [] | [ExternalBlob],
  'views' : bigint,
  'hidden' : boolean,
  'description' : string,
  'videoFile' : ExternalBlob,
  'category' : string,
  'uploader' : Principal,
  'uploadTime' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], Comment>,
  'addVideoToPlaylist' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal, string], undefined>,
  'bulkFeatureVideos' : ActorMethod<[Array<string>], undefined>,
  'bulkHideVideos' : ActorMethod<[Array<string>], undefined>,
  'bulkRemoveVideos' : ActorMethod<[Array<string>], undefined>,
  'createPlaylist' : ActorMethod<[string], undefined>,
  'deleteComment' : ActorMethod<[string, string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getAdminActivityLog' : ActorMethod<[bigint], Array<AdminAction>>,
  'getAllReports' : ActorMethod<[], Array<[string, Array<Report>]>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerSubscriptions' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedVideos' : ActorMethod<[], Array<Video>>,
  'getPlatformSettings' : ActorMethod<[], PlatformSettings>,
  'getPlatformStats' : ActorMethod<
    [],
    {
      'bannedUsers' : bigint,
      'totalReports' : bigint,
      'totalVideos' : bigint,
      'totalUsers' : bigint,
      'suspendedUsers' : bigint,
    }
  >,
  'getTrendingVideos' : ActorMethod<[], Array<Video>>,
  'getUserPlaylists' : ActorMethod<[Principal], Array<PlaylistView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStatistics' : ActorMethod<
    [Principal],
    {
      'accountCreationDate' : [] | [Time],
      'totalVideos' : bigint,
      'subscriberCount' : bigint,
    }
  >,
  'getUserStatus' : ActorMethod<[Principal], SuspensionStatus>,
  'getVideo' : ActorMethod<[string], [] | [Video]>,
  'getVideoComments' : ActorMethod<[string], Array<Comment>>,
  'getVideoReports' : ActorMethod<[string], Array<Report>>,
  'getVideosByCategory' : ActorMethod<[string], Array<Video>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeVideo' : ActorMethod<[string], bigint>,
  'removeReportedVideo' : ActorMethod<[string], undefined>,
  'reportVideo' : ActorMethod<[string, string], undefined>,
  'restoreUser' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<[Principal, UserProfile]>>,
  'searchVideos' : ActorMethod<[string], Array<Video>>,
  'subscribeToChannel' : ActorMethod<[Principal], undefined>,
  'suspendUser' : ActorMethod<[Principal, string], undefined>,
  'updatePlatformSettings' : ActorMethod<[PlatformSettings], undefined>,
  'uploadVideo' : ActorMethod<
    [string, string, string, ExternalBlob, [] | [ExternalBlob], string],
    Video
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];