/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'text' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminAction = IDL.Record({
  'id' : IDL.Nat,
  'admin' : IDL.Principal,
  'actionType' : IDL.Text,
  'timestamp' : Time,
  'details' : IDL.Text,
  'affectedResource' : IDL.Text,
});
export const Report = IDL.Record({
  'timestamp' : Time,
  'reporter' : IDL.Principal,
  'reason' : IDL.Text,
  'videoId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'email' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'views' : IDL.Nat,
  'hidden' : IDL.Bool,
  'description' : IDL.Text,
  'videoFile' : ExternalBlob,
  'category' : IDL.Text,
  'uploader' : IDL.Principal,
  'uploadTime' : Time,
});
export const PlatformSettings = IDL.Record({
  'maxVideoSizeMB' : IDL.Nat,
  'allowedCategories' : IDL.Vec(IDL.Text),
  'moderationPolicies' : IDL.Text,
});
export const PlaylistView = IDL.Record({
  'name' : IDL.Text,
  'videos' : IDL.Vec(IDL.Text),
});
export const SuspensionStatus = IDL.Record({
  'status' : IDL.Variant({
    'active' : IDL.Null,
    'banned' : IDL.Null,
    'suspended' : IDL.Null,
  }),
  'admin' : IDL.Principal,
  'timestamp' : Time,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [Comment], []),
  'addVideoToPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'bulkFeatureVideos' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'bulkHideVideos' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'bulkRemoveVideos' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'createPlaylist' : IDL.Func([IDL.Text], [], []),
  'deleteComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getAdminActivityLog' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AdminAction)],
      ['query'],
    ),
  'getAllReports' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Report)))],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerSubscriptions' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getPlatformSettings' : IDL.Func([], [PlatformSettings], ['query']),
  'getPlatformStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'bannedUsers' : IDL.Nat,
          'totalReports' : IDL.Nat,
          'totalVideos' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'suspendedUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTrendingVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getUserPlaylists' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PlaylistView)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStatistics' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'accountCreationDate' : IDL.Opt(Time),
          'totalVideos' : IDL.Nat,
          'subscriberCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserStatus' : IDL.Func([IDL.Principal], [SuspensionStatus], ['query']),
  'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(Video)], ['query']),
  'getVideoComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getVideoReports' : IDL.Func([IDL.Text], [IDL.Vec(Report)], ['query']),
  'getVideosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'removeReportedVideo' : IDL.Func([IDL.Text], [], []),
  'reportVideo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'restoreUser' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'subscribeToChannel' : IDL.Func([IDL.Principal], [], []),
  'suspendUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updatePlatformSettings' : IDL.Func([PlatformSettings], [], []),
  'uploadVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Opt(ExternalBlob),
        IDL.Text,
      ],
      [Video],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'text' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminAction = IDL.Record({
    'id' : IDL.Nat,
    'admin' : IDL.Principal,
    'actionType' : IDL.Text,
    'timestamp' : Time,
    'details' : IDL.Text,
    'affectedResource' : IDL.Text,
  });
  const Report = IDL.Record({
    'timestamp' : Time,
    'reporter' : IDL.Principal,
    'reason' : IDL.Text,
    'videoId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'email' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'views' : IDL.Nat,
    'hidden' : IDL.Bool,
    'description' : IDL.Text,
    'videoFile' : ExternalBlob,
    'category' : IDL.Text,
    'uploader' : IDL.Principal,
    'uploadTime' : Time,
  });
  const PlatformSettings = IDL.Record({
    'maxVideoSizeMB' : IDL.Nat,
    'allowedCategories' : IDL.Vec(IDL.Text),
    'moderationPolicies' : IDL.Text,
  });
  const PlaylistView = IDL.Record({
    'name' : IDL.Text,
    'videos' : IDL.Vec(IDL.Text),
  });
  const SuspensionStatus = IDL.Record({
    'status' : IDL.Variant({
      'active' : IDL.Null,
      'banned' : IDL.Null,
      'suspended' : IDL.Null,
    }),
    'admin' : IDL.Principal,
    'timestamp' : Time,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [Comment], []),
    'addVideoToPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'bulkFeatureVideos' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'bulkHideVideos' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'bulkRemoveVideos' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'createPlaylist' : IDL.Func([IDL.Text], [], []),
    'deleteComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getAdminActivityLog' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AdminAction)],
        ['query'],
      ),
    'getAllReports' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Report)))],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getPlatformSettings' : IDL.Func([], [PlatformSettings], ['query']),
    'getPlatformStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'bannedUsers' : IDL.Nat,
            'totalReports' : IDL.Nat,
            'totalVideos' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'suspendedUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTrendingVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getUserPlaylists' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PlaylistView)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStatistics' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'accountCreationDate' : IDL.Opt(Time),
            'totalVideos' : IDL.Nat,
            'subscriberCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserStatus' : IDL.Func([IDL.Principal], [SuspensionStatus], ['query']),
    'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(Video)], ['query']),
    'getVideoComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getVideoReports' : IDL.Func([IDL.Text], [IDL.Vec(Report)], ['query']),
    'getVideosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'removeReportedVideo' : IDL.Func([IDL.Text], [], []),
    'reportVideo' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'restoreUser' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'subscribeToChannel' : IDL.Func([IDL.Principal], [], []),
    'suspendUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updatePlatformSettings' : IDL.Func([PlatformSettings], [], []),
    'uploadVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(ExternalBlob),
          IDL.Text,
        ],
        [Video],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };